enable_fire: true
enable_person_gate: false
enable_violence: true
fire_allowed_labels:
- fire
- flame
fire_backend: yolov5
fire_color_gate_enabled: true
fire_color_min_ratio: 0.15
fire_iou_min: 0.3
fire_min_area: 600
fire_model_weights: models/best.pt
fire_motion_min_ratio: 0.02
fire_release_frames: 2
fire_sustain_frames: 2
fire_threshold: 0.5
fps: 8
person_conf_threshold: 0.35
person_every_n: 3
person_max_pair_distance_ratio: 0.18
person_min_pair_iou: 0.05
person_ttl_seconds: 1.0
post_roll_seconds: 5
pre_roll_seconds: 3
recording_enabled: false
recordings_dir: recordings
violence_ema_alpha: 0.6
violence_min_persons: 2
violence_model_path: models/violence_model.keras
violence_motion_min_ratio: 0.02
violence_release_frames: 3
violence_sequence_length: 16
violence_sustain_frames: 4
violence_threshold: 0.6
