enable_fire: true
enable_person_gate: true
enable_violence: true
fire_allowed_labels:
- fire
fire_backend: yolov5
fire_color_gate_enabled: true
fire_color_min_ratio: 0.2
fire_color_min_ratio_small: 0.14
fire_color_small_area: 900
fire_every_n: 3
fire_infer_size: 640
fire_iou_min: 0.4
fire_min_area: 1000
fire_model_weights: models/best.pt
fire_motion_min_ratio: 0.03
fire_release_frames: 2
fire_sustain_frames: 4
fire_threshold: 0.62
fps: 8
person_conf_threshold: 0.35
person_every_n: 3
person_infer_size: 512
person_max_pair_distance_ratio: 0.15
person_min_pair_iou: 0.12
person_model_name: yolov5s
person_require_proximity: false
person_ttl_seconds: 1.5
post_roll_seconds: 5
pre_roll_seconds: 3
recording_enabled: false
recordings_dir: recordings
violence_ema_alpha: 0.7
violence_min_persons: 2
violence_model_path: models/violence_model.keras
violence_motion_min_ratio: 0.04
violence_release_frames: 3
violence_sequence_length: 16
violence_sustain_frames: 6
violence_threshold: 0.8
